Improve performance of fetching members.
EternalCodeTeam/website pull request #70
Opened 2024-02-19 01:50 UTC by vLuckyyy

Average time of page loading before changes:

![image](https://github.com/EternalCodeTeam/website/assets/65517973/d87e04e9-0166-4bef-b618-c5d963f2bfc9)

Average time of page loading after changes:
![image](https://github.com/EternalCodeTeam/website/assets/65517973/ab137d2e-d5d8-444c-acda-3c6d902db0b0)

2024-02-19 06:31 UTC, Hyd3r1 approved these changes

2024-02-19 14:09 UTC, Rollczi requested changes

2024-02-19 14:09 UTC, Rollczi commented on components/team/Team.vue
> +interface MemberData {
TeamMember

2024-02-19 14:09 UTC, Rollczi commented on components/team/Team.vue
> +interface Member {
Team

2024-02-19 14:09 UTC, Rollczi commented on components/team/Team.vue
> +  data: MemberData[];
members: TeamMember[];

2024-02-21 14:40 UTC, CitralFlo approved these changes

2024-02-23 20:53 UTC, vLuckyyy commented
In Next.js it's automated. #71

2024-02-23 20:53 UTC, closed without merging