Cooking v3
EternalCodeTeam/website pull request #72
Opened 2024-02-21 20:27 UTC by vLuckyyy

2024-03-03 23:09 UTC, CitralFlo commented
The only issue I see:
![image](https://github.com/EternalCodeTeam/website/assets/80779749/a3c70020-bf62-4041-934a-6e5fdd1ff80b)
It disturbs the whole content layout

2024-03-03 23:18 UTC, CitralFlo approved these changes
The code looks good, Site is responsible and looks CLEAN 🔥

2024-03-04 08:19 UTC, Hyd3r1 requested changes

2024-03-04 08:19 UTC, Hyd3r1 commented on app/api/project/route.ts
> +    `https://cms.eternalcode.pl/api/projects?populate=*`,
When u use .env, please use it in whole code

2024-03-04 08:19 UTC, Hyd3r1 commented on app/api/team/route.ts
> +    `https://cms.eternalcode.pl/api/team-members?populate=*`,
Again, what if we change URL? 🤷‍♂️

2024-03-06 22:09 UTC, merged